### ISSUE TITLE
Press-to-save button - ensure it works

### ISSUE THREAD

**Issue by MirandaEcho** [INN/link-roundups#141] opened 2019-04-16 21:51 UTC
Ensure press-to-save button works

**Comment by benlk** [comment] 2019-04-29 23:31
Closing this as a duplicate of https://github.com/INN/link-roundups/issues/130, but it looks like this feature is gone for good unless we're willing to build our own version of WordPress' press-ot-save bookmarklet. That feature was removed in WordPress 4.9.

**Closed by benlk** 2019-04-29 23:31 UTC
